# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boundaryLayerv6.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Boundarylayer(object):
    def setupUi(self, Boundarylayer):
        Boundarylayer.setObjectName("Boundarylayer")
        Boundarylayer.resize(800, 599)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        Boundarylayer.setFont(font)
        Boundarylayer.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../plume_ZGo_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Boundarylayer.setWindowIcon(icon)
        Boundarylayer.setWindowOpacity(1.0)
        self.t = QtWidgets.QWidget(Boundarylayer)
        self.t.setObjectName("t")
        self.frame = QtWidgets.QFrame(self.t)
        self.frame.setGeometry(QtCore.QRect(10, 60, 176, 151))
        self.frame.setObjectName("frame")
        self.Input = QtWidgets.QVBoxLayout(self.frame)
        self.Input.setObjectName("Input")
        self.FluidLabel = QtWidgets.QLabel(self.frame)
        self.FluidLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FluidLabel.setAutoFillBackground(False)
        self.FluidLabel.setObjectName("FluidLabel")
        self.Input.addWidget(self.FluidLabel, 0, QtCore.Qt.AlignHCenter)
        self.FluidSel = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FluidSel.setFont(font)
        self.FluidSel.setAcceptDrops(True)
        self.FluidSel.setFrame(True)
        self.FluidSel.setObjectName("FluidSel")
        self.FluidSel.addItem("")
        self.FluidSel.addItem("")
        self.Input.addWidget(self.FluidSel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.Input.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.Temp = QtWidgets.QLineEdit(self.frame)
        self.Temp.setText("")
        self.Temp.setObjectName("Temp")
        self.Input.addWidget(self.Temp)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.t)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 70, 291, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.verticalLayoutWidget)
        self.formLayout.setContentsMargins(0, 6, 0, 0)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.Dens = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Dens.setObjectName("Dens")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Dens)
        self.KinViscosity = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.KinViscosity.setObjectName("KinViscosity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.KinViscosity)
        self.DinViscosity = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.DinViscosity.setObjectName("DinViscosity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.DinViscosity)
        self.denOut = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.denOut.setObjectName("denOut")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.denOut)
        self.kinVisOut = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kinVisOut.setObjectName("kinVisOut")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kinVisOut)
        self.dinVisOut = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dinVisOut.setObjectName("dinVisOut")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dinVisOut)
        self.ThermViscosity = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ThermViscosity.setObjectName("ThermViscosity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ThermViscosity)
        self.therVisOut = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.therVisOut.setObjectName("therVisOut")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.therVisOut)
        self.line1 = QtWidgets.QFrame(self.t)
        self.line1.setGeometry(QtCore.QRect(230, 50, 3, 141))
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QFrame(self.t)
        self.line2.setGeometry(QtCore.QRect(290, 60, 3, 141))
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.ExitButton = QtWidgets.QPushButton(self.t)
        self.ExitButton.setGeometry(QtCore.QRect(360, 360, 97, 27))
        self.ExitButton.setObjectName("ExitButton")
        Boundarylayer.setCentralWidget(self.t)
        self.menubar = QtWidgets.QMenuBar(Boundarylayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        Boundarylayer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Boundarylayer)
        self.statusbar.setObjectName("statusbar")
        Boundarylayer.setStatusBar(self.statusbar)

        self.retranslateUi(Boundarylayer)
        QtCore.QMetaObject.connectSlotsByName(Boundarylayer)

    def retranslateUi(self, Boundarylayer):
        _translate = QtCore.QCoreApplication.translate
        Boundarylayer.setWindowTitle(_translate("Boundarylayer", "Boundary Layer Estimation "))
        self.FluidLabel.setText(_translate("Boundarylayer", "Fluid"))
        self.FluidSel.setItemText(0, _translate("Boundarylayer", "water"))
        self.FluidSel.setItemText(1, _translate("Boundarylayer", "air"))
        self.label.setText(_translate("Boundarylayer", "Temperature[Cº]"))
        self.Dens.setText(_translate("Boundarylayer", "density [kg/m^3]"))
        self.KinViscosity.setText(_translate("Boundarylayer", "kinematic viscosity [m^2/s]"))
        self.DinViscosity.setText(_translate("Boundarylayer", "dynamic viscosity [Pa s]"))
        self.denOut.setText(_translate("Boundarylayer", "TextLabel"))
        self.kinVisOut.setText(_translate("Boundarylayer", "TextLabel"))
        self.dinVisOut.setText(_translate("Boundarylayer", "TextLabel"))
        self.ThermViscosity.setText(_translate("Boundarylayer", "thermal viscosity [Pa s]"))
        self.therVisOut.setText(_translate("Boundarylayer", "TextLabel"))
        self.ExitButton.setText(_translate("Boundarylayer", "Exit"))

    def exi(self):
        self.ExitButton.connectNotify("exit")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Boundarylayer = QtWidgets.QMainWindow()
    ui = Ui_Boundarylayer()
    ui.setupUi(Boundarylayer)
    Boundarylayer.show()
    sys.exit(app.exec_())

